### ISSUE TITLE
More Branches

### ISSUE THREAD

**Issue by marzinx3** [javabrewery/brew-chat#5]
Hey guys i think we need to more branches 1 for test/dev where we will be working on then the next for qa/unit testing and the final one will be the master branch/prod internment once we get it to this state we can add it to the play store and all of us can downloaded and use the app.

**Comment by arreche** [comment]
Depends on what you want to do. I think it is a good point to discuss on [Slack](https://thejavabrewery.slack.com)
- https://www.atlassian.com/git/tutorials/comparing-workflows
- http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by jephillips** [comment]
If we are going with the continuous integration paradigm we might want to be using feature toggles instead of branches. 

http://martinfowler.com/bliki/FeatureToggle.html
